language: python
sudo: required
before_script:
    - sudo apt-get update
    - sudo apt-get install -y libsodium-dev
    - sudo pip install --upgrade pip setuptools
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
    - SINGLE_APP=1
    - DEFAULT_RELEASE_2020_04_19=2020-01-01
  matrix:
    - SANDBOX_MODE=
    - SANDBOX_MODE=True
cache:
  directories:
    - eggs
before_install:
  - pip install --user -r requirements.txt
script:
  - python setup.py test
after_success:
  - bin/coveralls
