language: python
services: docker
sudo: required
before_script:
    - sudo apt-get update
    - sudo apt-get install -y libsodium-dev
    - sudo pip install --upgrade pip setuptools
    - sudo 
python:
  - "2.7"
env:
  global:
    - TZ=Europe/Kiev
    - SINGLE_APP=1
    - DEFAULT_RELEASE_2020_04_19=2020-01-01
    - COUCHDB_USER=op   
    - COUCHDB_PASSWORD=op
  matrix:
    - SANDBOX_MODE=
    - SANDBOX_MODE=True
cache:
  directories:
    - eggs
before_install:
  - pip install -r requirements.txt
  - docker run -d --net=host couchdb:1.7.2
  - echo '127.0.0.1  couchdb' >> /etc/hosts
script:
  - python setup.py test
after_success:
  - bin/coveralls
