language: gneric
# python:
#   - "2.7"
services: docker
# addons:
#   hosts:
#     - couchdb
sudo: required
# before_script:
#     - sudo apt-get update
#     - sudo apt-get install -y libsodium-dev
python:
  - "2.7"
env:
  global:
    - TZ=Europe/Kiev
    - SINGLE_APP=1
    - COUCHDB_USER=op   
    - COUCHDB_PASSWORD=op
# cache:
#   directories:
#     - eggs
before_install:
#   - pip install -r requirements.txt
  - docker run -d couchdb:1.7.2
jobs:
  include:
    - test:
      name: sandbox
      env: 
        - DB_NAME=test_sandbox
        - SANDBOX_MODE=1
    - test:
      name: prod
      env: 
        - SANDBOX_MODE=
        - DB_NAME=test_prod
    - test:
      name: sandbox_020_04_19
      env: 
        - DB_NAME=test_sandbox_2020_04_19
        - SANDBOX_MODE=1
        - DEFAULT_RELEASE_2020_04_19=2020-01-01
    - test:
      name: prod_020_04_19
      env: 
        - SANDBOX_MODE=
        - DB_NAME=test_prod_2020_04_1
        - DEFAULT_RELEASE_2020_04_19=2020-01-01
script:
  - docker build -t api .
  - | 
      docker run -it api sh -c 'cd /app && 
      py.test $TESTS_PATH --cov=$COV_PATH --cov-config=$COV_FILE -v --color=yes --dist=each 
      --tx=popen//id=sand//env:DB_NAME=test_sandbox//env:SANDBOX_MODE=1//env:SINGLE_APP=1 
      --tx=popen//id=prod//env:DB_NAME=test_prod//env:SANDBOX_MODE=//env:SINGLE_APP=1 
      --tx=popen//id=sand_relsease_2020_04_19//env:DB_NAME=test_sandbox_2020_04_19//env:SANDBOX_MODE=1//env:SINGLE_APP=1//env:DEFAULT_RELEASE_2020_04_19=2020-01-01 
      --tx=popen//id=prod_relsease_2020_04_19//env:DB_NAME=test_prod_2020_04_19//env:SANDBOX_MODE=//env:SINGLE_APP=1//env:DEFAULT_RELEASE_2020_04_19=2020-01-01 
      > /proc/1/fd/1'
# after_success:
#   - bin/coveralls
