language: python
services: docker
addons:
  hosts:
    - couchdb
sudo: required
before_script:
    - sudo apt-get update
    - sudo apt-get install -y libsodium-dev
    - sudo pip install --upgrade pip setuptools
python:
  - "2.7"
env:
  global:
    - TZ=Europe/Kiev
    - SINGLE_APP=1
    - COUCHDB_USER=op   
    - COUCHDB_PASSWORD=op
cache:
  directories:
    - eggs
before_install:
  - pip install -r requirements.txt
  - docker run -d --net=host couchdb:1.7.2
jobs:
  include:
    - sandbox:
      env: 
        - DB_NAME=test_sandbox
        - SANDBOX_MODE=1
    - prod: 
      env: 
        - SANDBOX_MODE=
        - DB_NAME=test_prod
    - sndbox_2020_04_19:
      env: 
        - DB_NAME=test_sandbox_2020_04_19
        - SANDBOX_MODE=1
        - DEFAULT_RELEASE_2020_04_19=2020-01-01
    - prod_2020_04_19: 
      env: 
        - SANDBOX_MODE=
        - DB_NAME=test_prod_2020_04_1
        - DEFAULT_RELEASE_2020_04_19=2020-01-01
script:
  - python setup.py test
after_success:
  - bin/coveralls
