language: gneric
# python:
#   - "2.7"
services: docker
addons:
  hosts:
    - couchdb
sudo: required
# before_script:
#     - sudo apt-get update
#     - sudo apt-get install -y libsodium-dev

git:
  depth: 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: pontostroy

env:
  global:
    - TZ=Europe/Kiev
    - SINGLE_APP=1
    - COUCHDB_USER=op   
    - COUCHDB_PASSWORD=op
# cache:
#   directories:
#     - eggs
before_install:
#   - pip install -r requirements.txt
  - docker run -d --net=host couchdb:1.7.2
jobs:
  include:
    - build:
      name: build
      script:
         - docker build -t api .
    - test:
      name: test_relocation_api
      env: 
        - TESTS_PATH: src/openprocurement/relocation/api/tests
        - COV_PATH: src/openprocurement/relocation/api
        - COV_FILE: .coveragerc
    - test:
      name: test_tender_esco
      env: 
         - TESTS_PATH: src/openprocurement/tender/esco/tests
         - COV_PATH: src/openprocurement/tender/esco
         - COV_FILE: .coveragerc
script:
  - | 
      docker run -it --net=host api sh -c 'cd /app && 
      py.test $TESTS_PATH --cov=$COV_PATH --cov-config=$COV_FILE -v --color=yes --dist=each \
      --tx=popen//id=sand//env:DB_NAME=test_sandbox//env:SANDBOX_MODE=1//env:SINGLE_APP=1 \
      --tx=popen//id=prod//env:DB_NAME=test_prod//env:SANDBOX_MODE=//env:SINGLE_APP=1 \
      --tx=popen//id=sand_relsease_2020_04_19//env:DB_NAME=test_sandbox_2020_04_19//env:SANDBOX_MODE=1//env:SINGLE_APP=1//env:DEFAULT_RELEASE_2020_04_19=2020-01-01 \
      --tx=popen//id=prod_relsease_2020_04_19//env:DB_NAME=test_prod_2020_04_19//env:SANDBOX_MODE=//env:SINGLE_APP=1//env:DEFAULT_RELEASE_2020_04_19=2020-01-01 \
      > /proc/1/fd/1'
# after_success:
#   - bin/coveralls
